// Liste des artistes indiens fictifs avec leur style musical
const indiaArtists = [
  "Advait Nair Ji → Hindustani Techno",
  "Yash Verma Ji → Punjabi Drill",
  "DJ Ved ben → BollyPhonk",
  "Yash Roy → Sufi Electronique",
  "Dev Roy → Gharana Garage",
  "Pranav Devi → Vocal Chutney",
  "DJ Tanish Ghosh → Mystic Sarangi",
  "Kiran Didi → BollyPhonk",
  "Akhil Rao → Sitarwave",
  "Pranav Nair → Mumbai Bass",
  "Gaurav Didi → Indian Lo-Fi",
  "Dev Ghosh → Mystic Sarangi",
  "Zayan Shree → Raga House",
  "Akhil Lakshmi Ji → Thumri Ambient",
  "Varun Saraswati → Rajasthani Psytrance",
  "Ishaan Bai → Sindhi Synthwave",
  "DJ Rahul Pillai → Carnatic Chill",
  "Arjun Sharma → Mumbai Bass",
  "DJ Samar Saha → Mystic Sarangi",
  "Tanish Chatterjee → Sufi Electronique",
  "Bharat Ghosh → Gharana Garage",
  "Samar Rani → Vocal Chutney",
  "Dhruv Chatterjee → Qawwali Glitch",
  "DJ Ved Saha → Raga Jungle",
  "Yash Chatterjee → Lavani Trap",
  "Om Priya → Punjabi Drill",
  "Varun Devi → Carnatic Chill",
  "DJ Utkarsh Bai → Sindhi Synthwave",
  "Yash Gupta → Raga Jungle",
  "DJ Vihaan Banerjee → Sitarwave",
  "Advait ben → Sufi Electronique",
  "DJ Amar Shree → Bollywood Bass",
  "Anand Chatterjee → Desi Hyperpop",
  "Utkarsh Rao → BollyPhonk",
  "Samar Lakshmi → Raga House",
  "Ashwin Sharma → Hindustani Techno",
  "Eeshan Bai → Indie Khayal",
  "Anand Banerjee → Hindustani Techno",
  "Yash Kaur → Dholstep",
  "DJ Varun Kumari → Neon Bollywood",
  "DJ Dev Das → Mystic Sarangi",
  "Tanish Priya → Lavani Trap",
  "Kiran Shree → Raga House",
  "Amar Sharma → Mumbai Bass",
  "Ved Devi Ji → Indian Lo-Fi",
  "DJ Ishaan Das → Dholstep",
  "DJ Akhil Saha → Thumri Ambient",
  "Gaurav Menon → Qawwali Glitch",
  "Anand Singh → Hindustani Techno",
  "Gaurav Bai → Indian Lo-Fi",
  "DJ Om Iyer → Qawwali Glitch",
  "Vihaan Singh → Hindustani Techno",
  "DJ Chaitanya Nair → Hindustani Techno",
  "Darshan Nair → Gharana Garage",
  "Jai Bai → Raga House",
  "DJ Samar Priya → Gharana Garage",
  "Jai Patel → Sindhi Synthwave",
  "Bharat Verma → Rajasthani Psytrance",
  "Om Dutta → Bollywood Bass",
  "DJ Akhil Lakshmi → Dholstep",
  "Nikhil Ghosh → Rajasthani Psytrance",
  "Ishaan Patel → Retro Indi-Pop",
  "Neel Saraswati → Dholstep",
  "Ashwin Saraswati → Sitarwave",
  "Tanish Lakshmi → Sitarwave",
  "Eeshan Saraswati → Indie Khayal",
  "Ved Saraswati → Gharana Garage",
  "DJ Bharat Nair → Vocal Chutney",
  "Samar Lakshmi → Kathak Drum & Bass",
  "DJ Eeshan Priya → Sindhi Synthwave",
  "Yash Didi → BollyPhonk",
  "Anand Didi → Bhangra Future Bass",
  "Lakshya Chatterjee → Neon Bollywood",
  "DJ Zayan Joshi → Mystic Sarangi",
  "Dhruv Saha → Sufi Electronique",
  "Gaurav Saraswati → Thumri Ambient",
  "Siddh Gupta → Mumbai Bass",
  "Kiran Chatterjee → Punjabi Drill",
  "Ishaan Iyer → Desi Trap",
  "Utkarsh ben Ji → Retro Indi-Pop",
  "Vihaan Menon → Kerala Wave",
  "Aarav Kaur → Baul Beats",
  "DJ Lakshya Roy → Desi Hyperpop",
  "Harsh Kumari → Classical Fusioncore",
  "Neel Rani → Goa Trance 2.0",
  "DJ Mihir ben → Tabla Dub"
];

// Fonction pour sélectionner aléatoirement 3 artistes
function selectRandomIndiaArtists(count: number = 3): string[] {
  const shuffled = [...indiaArtists].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
}

// Exemple d'utilisation : sortir 3 noms aléatoires
const selectedArtists = selectRandomIndiaArtists(3);
console.log("Artistes indiens sélectionnés aléatoirement :");
selectedArtists.forEach(artist => console.log(artist));

export { indiaArtists, selectRandomIndiaArtists };