// Liste des artistes mexicains fictifs avec leur style musical
const mexicoArtists = [
  "El Néon Ramírez – Corridos Tumbados",
  "La Beloda – Neoperreo",
  "Junior Salazar – Trap Corrido",
  "DJ Fuego 666 – Guaracha Mexicana",
  "Los Plebes del Sur – Sierreño Moderno",
  "Rayo Chávez – Mexa Rap",
  "Santa Muerte Flow – Dark Regional / Corridos Tristes",
  "El Jaguar de Tijuana – Latin Trap",
  "Cumbia Loca – Cumbia Rebajada",
  "Diablo Ortiz – Narco Corridos",
  "Reina del Norte – Banda UPA",
  "Peso Pluma Fake – Corridos Bélicos",
  "Caliente Mendoza – Perreo Intenso",
  "Lobo Gris MX – Regional Mexicano 2020s",
  "La Bruja Sonora – Electrónica Folclórica",
  "Zorro 420 – Dembow Mexa",
  "Místico Guzmán – Lo-Fi Corrido",
  "El Chingón Vásquez – Grupero Urbano",
  "Tormenta Rojas – Techno Norteño",
  "Sangre Nueva – SAD Corridos",
  "DJ Águila Negra – Moombahton Mexicano",
  "La Villana – Reggaeton Mexicano",
  "Retro Jiménez – Indie Mexa",
  "Corazón Roto – Ranchera Alternativa",
  "El Fantasma de Culiacán – Corridos Tumbados Oscuros",
  "Nube Morada – Chill Mexa",
  "MC Cobra – Mexa Rap old school",
  "Las Morras del Barrio – Cumbia Sonidera",
  "Oscuro Reyes – Dark Regional",
  "Viento del Desierto – Sierreño Acústico Moderno",
  "El Sol de Sinaloa – Corridos Épicos",
  "Frío Aguilar – Trap Corrido Melancólico",
  "La Loba – Neoperreo oscuro",
  "Hyper Pablito – Hyperpop Regional",
  "Salvaje Torres – Afro-Mexicano",
  "Estrella Fugaz – Bachata Urbana Mexa",
  "DJ Sombras – Electrocumbia",
  "El Rey Caído – Corridos Tristes",
  "Marea Roja – Post-Punk Mexicano",
  "Claro Luna – Salsa Chida",
  "El Coyote Loco – Regional Mexicano Fusión",
  "Perla Negra – Bolero Trap",
  "Trueno Martínez – Guaracha Hard",
  "La Santa Diabla – Dark Corrido",
  "Ráfaga Ortiz – Mexa Drill",
  "Sol Ardiente – Cumbia Digital",
  "El Cuervo – Narco Corridos New Wave",
  "Dulce Veneno – Perreo Romántico",
  "Medianoche MX – Lo-Fi Regional",
  "El Último Jaguar – Corridos Tumbados Clásicos",
  "La Brisa – Chill Corrido",
  "Furia Azteca – Latin Trap agresivo",
  "El Niño del Maíz – Sierreño Experimental",
  "Vampiro Norteño – Dark Regional",
  "La Reina del Perreo – Neoperreo Queen",
  "Polvo Cósmico – Electrónica Folclórica",
  "El Lobo Solitario – Corridos Introspectivos",
  "Candela – Dembow Mexa 2025",
  "Espejo Roto – Indie Regional",
  "El Profeta – Corridos Filosóficos",
  "Marea Verde – Cumbia Psicodélica",
  "Sangre y Arena – Ranchera Dark",
  "DJ Eclipse – Techno Mexa",
  "La Viuda Negra – Trap Corrido Femenino",
  "El Cometa – Hyper Regional",
  "Pura Candela – Guaracha Femenina",
  "El Ausente – Corridos de Desamor",
  "Niebla Roja – Dark Mexa Rap",
  "La Chida – Grupero Urbano 2.0",
  "Rayo del Pacífico – Sierreño Surf",
  "El Silencio – Minimal Corrido",
  "Corazón de Neón – Synthwave Mexa",
  "La Tormenta – Perreo Apocalíptico",
  "El Renacido – Corridos de Regreso",
  "Flor de Muerto – Cumbia Gótica",
  "El Último Trago – Bolero Trap triste",
  "Diablo de Cristal – Neoperreo oscuro",
  "La Herida – SAD Regional",
  "El Amanecer – Corridos Esperanza",
  "Infinito MX – Regional Mexicano Cósmico"
];

// Fonction pour sélectionner aléatoirement 3 artistes
function selectRandomMexicoArtists(count: number = 3): string[] {
  const shuffled = [...mexicoArtists].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
}

// Exemple d'utilisation : sortir 3 noms aléatoires
const selectedArtists = selectRandomMexicoArtists(3);
console.log("Artistes mexicains sélectionnés aléatoirement :");
selectedArtists.forEach(artist => console.log(artist));

export { mexicoArtists, selectRandomMexicoArtists };