// Liste des artistes japonais fictifs avec leur style musical
const japanArtists = [
  "Aki Nebula → Synthwave",
  "Haruka Mirror → City Pop",
  "YUU☆Liminal → Hyperpop",
  "Sora Velvet → Dream Pop",
  "Rin 404 → Glitch Pop",
  "Mio Eclipse → Kawaii Future Bass",
  "KAITO×Neon → J-Core",
  "Tsukineko → Vocaloid / Utaite",
  "Nao Fractal → IDM",
  "Sakura Ghost → Vaporwave",
  "Reimi Circuit → Electropop",
  "LUNAR∴System → Nightcore",
  "Asuka Nova → Future Bass",
  "Hikari 1989 → Shibuya-kei revival",
  "Yume Spectra → Chillhop",
  "Shion Crimson → Visual Kei",
  "Kazu Pixel → J-Hip Hop / Trap",
  "Noiryu → Lo-Fi Beats",
  "CV:Stella Void → Doujin / Vocaloid producer",
  "Azure Project → J-Pop expérimental",
  "Tsubaki_m1rror → Plunderphonics",
  "Echo Starlight → Shoegaze",
  "0Rin. Oracle → Breakcore",
  "Novaharu → J-Rock moderne",
  "Kiraneon → Hyperpop",
  "Lune & The Moons → Alternative J-Pop",
  "Sakurake 404 → J-Core",
  "Yuusu Liminal → Ambient",
  "Rei Dreamscape → Downtempo",
  "Noir×∞ → Techno / Darkwave",
  "Hanabi Circuit → Happy Hardcore",
  "Stellamoon → Synthpop",
  "CV:Kazu Velvet → Utaite ballad",
  "Tsuki_n3on → Nightcore",
  "Mioyonova → Math Rock",
  "Haru Phantom → Post-Rock",
  "RIN×Spectra → Drum & Bass",
  "Azureto → J-Rap / Trap",
  "Yumeko Ghost → Lo-Fi Hip Hop",
  "Shion404 → Glitch Hop",
  "NOVA☆Collective → J-Pop groupe",
  "Kaito Eclipse → Symphonic Power Metal",
  "Sakurineko → Kawaii Bass",
  "0Luna. Mirror → Vaporwave",
  "Hikarino Yoru → City Pop 80s revival",
  "AsukA☆System → Electropop",
  "Rei Liminal → Experimental Electronic",
  "Tsukiyo Nebula → Trance",
  "Noir Sakura → Dark J-Pop",
  "CV:Echo Crimson → Doujin rock",
  "Yume Circuit → Synthwave",
  "Kirapixel → Hyperpop",
  "Sora & The Void → Dream Pop / Shoegaze",
  "Mio×404 → Breakcore",
  "Hanano Neon → J-Pop futuriste",
  "Stellakei → Visual Kei pop",
  "Luneke → Utaite / cover artist",
  "Novatsuki → J-Indie",
  "Azure Ghost → Chillwave",
  "Rin Dreamweaver → Ambient Pop",
  "KAITO 2049 → Cyberpunk Synth",
  "Sakurano Echo → Lo-Fi Beats",
  "Shion Nova → Future Bass",
  "0Haru. Oracle → Plunderphonics",
  "Yumepop → Kawaii Hyperpop",
  "Tsukine Fractal → IDM",
  "Noir Velvet → Dark Synthpop",
  "CV:Rin Starlight → Vocaloid-style producer",
  "Hikari Syndicate → J-Rock / Math Rock",
  "Asuka 198X → Retro City Pop",
  "Neonsakura → Electropop",
  "Lune Pixel → Glitch Pop",
  "Sora Crimson → Post-Hardcore",
  "Mio Liminal → Experimental J-Pop",
  "Kiradream → Shibuya-kei",
  "YUU×Void → Trap / J-Rap",
  "Stellanoir → Dark Pop",
  "CV:Tsuki Nebula → Doujin Trance",
  "Sakurake Neon → J-Core",
  "Rei 404 & Friends → Glitchcore",
  "Hanabira System → Happy Hardcore",
  "Novamoon → Dream Pop",
  "Azureto Echo → Shoegaze",
  "Rinchi Nova → Hyperpop",
  "Kaito Liminal → Chillhop",
  "Yumeko Circuit → Synthwave",
  "Shion×Mirror → Vaporwave",
  "0Nao. Spectra → Nightcore",
  "Hikarino Phantom → City Pop",
  "Tsukiyo Velvet → Downtempo",
  "Noir Project → Alternative R&B",
  "CV:Asuka Neon → Utaite pop",
  "Sakurinebula → Future Bass",
  "Lune Collective → J-Pop girl group vibe",
  "Kiratsuki → J-Hip Hop",
  "Stellapop → Kawaii Future Bass",
  "Reikei → Visual Kei ballad",
  "Yume 404 → Glitch Pop",
  "Sora Dreamscape → Ambient Pop",
  "Mio×∞ → Experimental Electronic"
];

// Fonction pour sélectionner aléatoirement 3 artistes
function selectRandomJapanArtists(count: number = 3): string[] {
  const shuffled = [...japanArtists].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
}

// Exemple d'utilisation : sortir 3 noms aléatoires
const selectedArtists = selectRandomJapanArtists(3);
console.log("Artistes japonais sélectionnés aléatoirement :");
selectedArtists.forEach(artist => console.log(artist));

export { japanArtists, selectRandomJapanArtists };